# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import log_collector_pb2 as proto_dot_log__collector__pb2


class LogCollectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartLog = channel.unary_unary(
                '/mlrun.LogCollector/StartLog',
                request_serializer=proto_dot_log__collector__pb2.StartLogRequest.SerializeToString,
                response_deserializer=proto_dot_log__collector__pb2.BaseResponse.FromString,
                )
        self.GetLogs = channel.unary_stream(
                '/mlrun.LogCollector/GetLogs',
                request_serializer=proto_dot_log__collector__pb2.GetLogsRequest.SerializeToString,
                response_deserializer=proto_dot_log__collector__pb2.GetLogsResponse.FromString,
                )
        self.GetLogSize = channel.unary_unary(
                '/mlrun.LogCollector/GetLogSize',
                request_serializer=proto_dot_log__collector__pb2.GetLogSizeRequest.SerializeToString,
                response_deserializer=proto_dot_log__collector__pb2.GetLogSizeResponse.FromString,
                )
        self.StopLogs = channel.unary_unary(
                '/mlrun.LogCollector/StopLogs',
                request_serializer=proto_dot_log__collector__pb2.StopLogsRequest.SerializeToString,
                response_deserializer=proto_dot_log__collector__pb2.BaseResponse.FromString,
                )
        self.DeleteLogs = channel.unary_unary(
                '/mlrun.LogCollector/DeleteLogs',
                request_serializer=proto_dot_log__collector__pb2.StopLogsRequest.SerializeToString,
                response_deserializer=proto_dot_log__collector__pb2.BaseResponse.FromString,
                )
        self.ListRunsInProgress = channel.unary_stream(
                '/mlrun.LogCollector/ListRunsInProgress',
                request_serializer=proto_dot_log__collector__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=proto_dot_log__collector__pb2.ListRunsResponse.FromString,
                )


class LogCollectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunsInProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogCollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartLog': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLog,
                    request_deserializer=proto_dot_log__collector__pb2.StartLogRequest.FromString,
                    response_serializer=proto_dot_log__collector__pb2.BaseResponse.SerializeToString,
            ),
            'GetLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=proto_dot_log__collector__pb2.GetLogsRequest.FromString,
                    response_serializer=proto_dot_log__collector__pb2.GetLogsResponse.SerializeToString,
            ),
            'GetLogSize': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogSize,
                    request_deserializer=proto_dot_log__collector__pb2.GetLogSizeRequest.FromString,
                    response_serializer=proto_dot_log__collector__pb2.GetLogSizeResponse.SerializeToString,
            ),
            'StopLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.StopLogs,
                    request_deserializer=proto_dot_log__collector__pb2.StopLogsRequest.FromString,
                    response_serializer=proto_dot_log__collector__pb2.BaseResponse.SerializeToString,
            ),
            'DeleteLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLogs,
                    request_deserializer=proto_dot_log__collector__pb2.StopLogsRequest.FromString,
                    response_serializer=proto_dot_log__collector__pb2.BaseResponse.SerializeToString,
            ),
            'ListRunsInProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.ListRunsInProgress,
                    request_deserializer=proto_dot_log__collector__pb2.ListRunsRequest.FromString,
                    response_serializer=proto_dot_log__collector__pb2.ListRunsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlrun.LogCollector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogCollector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mlrun.LogCollector/StartLog',
            proto_dot_log__collector__pb2.StartLogRequest.SerializeToString,
            proto_dot_log__collector__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mlrun.LogCollector/GetLogs',
            proto_dot_log__collector__pb2.GetLogsRequest.SerializeToString,
            proto_dot_log__collector__pb2.GetLogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLogSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mlrun.LogCollector/GetLogSize',
            proto_dot_log__collector__pb2.GetLogSizeRequest.SerializeToString,
            proto_dot_log__collector__pb2.GetLogSizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mlrun.LogCollector/StopLogs',
            proto_dot_log__collector__pb2.StopLogsRequest.SerializeToString,
            proto_dot_log__collector__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mlrun.LogCollector/DeleteLogs',
            proto_dot_log__collector__pb2.StopLogsRequest.SerializeToString,
            proto_dot_log__collector__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListRunsInProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mlrun.LogCollector/ListRunsInProgress',
            proto_dot_log__collector__pb2.ListRunsRequest.SerializeToString,
            proto_dot_log__collector__pb2.ListRunsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
