# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Prepare for SQLAlchemy 2 and Postgres

Revision ID: 528d9f5ea91d
Revises: 6925effc8fb1
Create Date: 2025-05-22 19:11:42.445053

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

import mlrun

# revision identifiers, used by Alembic.
revision = "528d9f5ea91d"
down_revision = "6925effc8fb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alert_activations",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "entity_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "entity_kind",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "event_kind",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "severity",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_configs_notifications",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "kind",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "message",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "severity",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "when",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "condition",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "sent_time",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_configs_notifications",
        "status",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "reason",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_states",
        "created",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_states",
        "last_updated",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_templates",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "artifacts",
        "key",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts",
        "uid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts",
        "updated",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_tags",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_tags",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "key",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "kind",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "producer_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "producer_uri",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "uid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "created",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "updated",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2_tags",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2_tags",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2_tags",
        "obj_name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "background_tasks",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "background_tasks",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "background_tasks",
        "created",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "background_tasks",
        "updated",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "background_tasks",
        "state",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "background_tasks",
        "error",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "data_versions",
        "version",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "data_versions",
        "created",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "datastore_profiles",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "datastore_profiles",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "datastore_profiles",
        "type",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "entities",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "entities",
        "value_type",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "entities_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "entities_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "created",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "updated",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "state",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "uid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets_tags",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets_tags",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets_tags",
        "obj_name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "created",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "updated",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "state",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "uid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors_tags",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors_tags",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors_tags",
        "obj_name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "features",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "features",
        "value_type",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "features_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "features_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "uid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "kind",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "state",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "updated",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions_tags",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions_tags",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "functions_tags",
        "obj_name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "hub_sources",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "hub_sources",
        "created",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "hub_sources",
        "updated",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints",
        "uid",
        existing_type=mysql.VARCHAR(collation="utf8mb3_bin", length=32),
        type_=sa.Uuid(),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints",
        "created",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints",
        "updated",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints_tags",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints_tags",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints_tags",
        "obj_name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "pagination_cache",
        "key",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "pagination_cache",
        "user",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "pagination_cache",
        "function",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "pagination_cache",
        "last_accessed",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "project_summaries",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "projects",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "description",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "owner",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "source",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "created",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "state",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "projects_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "projects_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "uid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "state",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "start_time",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "updated",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_notifications",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_notifications",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "kind",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "message",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "severity",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "when",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "condition",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "sent_time",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_notifications",
        "status",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "reason",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_tags",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_tags",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "schedules_v2",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "schedules_v2",
        "kind",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "desired_state",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "state",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "creation_time",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "cron_trigger_str",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "last_run_uri",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "next_run_time",
        existing_type=mysql.TIMESTAMP(fsp=3),
        type_=mlrun.db.sql_types.MicroSecondDateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2_labels",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2_labels",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    op.alter_column(
        "system_metadata",
        "key",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "system_metadata",
        "value",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "time_window_trackers",
        "key",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "name",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=mlrun.db.sql_types.Utf8BinText(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "time_window_trackers",
        "key",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "system_metadata",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "system_metadata",
        "key",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "schedules_v2_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "next_run_time",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "last_run_uri",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "cron_trigger_str",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "creation_time",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "state",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "desired_state",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "kind",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "schedules_v2",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "schedules_v2",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_tags",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_tags",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_notifications",
        "reason",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_notifications",
        "status",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "sent_time",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_notifications",
        "condition",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "when",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "severity",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "message",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "kind",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "runs_notifications",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "runs_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "updated",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "start_time",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "state",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "uid",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "projects_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "projects_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "state",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "created",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "source",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "owner",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "description",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "project_summaries",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "pagination_cache",
        "last_accessed",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "pagination_cache",
        "function",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "pagination_cache",
        "user",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "pagination_cache",
        "key",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "model_endpoints_tags",
        "obj_name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints_tags",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints_tags",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints",
        "updated",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints",
        "created",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "model_endpoints",
        "uid",
        existing_type=sa.Uuid(),
        type_=mysql.VARCHAR(collation="utf8mb3_bin", length=32),
        existing_nullable=True,
    )
    op.alter_column(
        "hub_sources",
        "updated",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "hub_sources",
        "created",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "hub_sources",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "functions_tags",
        "obj_name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "functions_tags",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "functions_tags",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "functions_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "functions_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "updated",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "state",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "kind",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "uid",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "functions",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "features_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "features_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "features",
        "value_type",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "features",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors_tags",
        "obj_name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors_tags",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors_tags",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "uid",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "state",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "updated",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "created",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_vectors",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets_tags",
        "obj_name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets_tags",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets_tags",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "uid",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "state",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "updated",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "created",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "feature_sets",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "entities_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "entities_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "entities",
        "value_type",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "entities",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "datastore_profiles",
        "type",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "datastore_profiles",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "datastore_profiles",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "data_versions",
        "created",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "data_versions",
        "version",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "background_tasks",
        "error",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "background_tasks",
        "state",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "background_tasks",
        "updated",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "background_tasks",
        "created",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "background_tasks",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "background_tasks",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "artifacts_v2_tags",
        "obj_name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2_tags",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2_tags",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "updated",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "created",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "uid",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "producer_uri",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "producer_id",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "kind",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_v2",
        "key",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_tags",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_tags",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_labels",
        "value",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts_labels",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts",
        "updated",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts",
        "uid",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "artifacts",
        "key",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_templates",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_states",
        "last_updated",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_states",
        "created",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_configs_notifications",
        "reason",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_configs_notifications",
        "status",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "sent_time",
        existing_type=mlrun.db.sql_types.MicroSecondDateTime(),
        type_=mysql.TIMESTAMP(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_configs_notifications",
        "condition",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "when",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "severity",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "message",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "kind",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs_notifications",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_configs",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_configs",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "severity",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "event_kind",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "entity_kind",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "entity_id",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "project",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_activations",
        "name",
        existing_type=mlrun.db.sql_types.Utf8BinText(),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
