name: Test Simple

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello World - Test workflow is working!" 